export const mockChats = [
  {
    id: "CH-001",
    user: "Nguyen Van A",
    agent: "Bot AI",
    status: "active",
    messages: 24,
    lastActive: "2 phut truoc",
  },
  {
    id: "CH-002",
    user: "Tran Thi B",
    agent: "Support (Human)",
    status: "resolved",
    messages: 12,
    lastActive: "1 gio truoc",
  },
  {
    id: "CH-003",
    user: "Guest_8392",
    agent: "Unassigned",
    status: "waiting",
    messages: 2,
    lastActive: "Vua xong",
  },
  {
    id: "CH-004",
    user: "Le Hoang C",
    agent: "Bot AI",
    status: "active",
    messages: 8,
    lastActive: "5 phut truoc",
  },
  {
    id: "CH-005",
    user: "Pham Dieu D",
    agent: "Bot AI",
    status: "escalated",
    messages: 45,
    lastActive: "10 phut truoc",
  },
];
